# Generated by Django 4.1 on 2022-08-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название цвета')),
                ('code', models.CharField(max_length=10, verbose_name='Код цвета')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название шрифта')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='fonts', verbose_name='Файл со шрифтом')),
            ],
            options={
                'verbose_name': 'Шрифт',
                'verbose_name_plural': 'Шрифты',
            },
        ),
        migrations.CreateModel(
            name='Frameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(max_length=20, verbose_name='Фреймворк')),
            ],
            options={
                'verbose_name': 'Фреймворк',
                'verbose_name_plural': 'Фреймворки',
            },
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_mobile', models.FileField(blank=True, default=None, null=True, upload_to='backgrounds/mobile', verbose_name='Фон для мобилки')),
                ('background_desktop', models.FileField(blank=True, default=None, null=True, upload_to='backgrounds/mobile', verbose_name='Фон для десктопа')),
                ('main_offer', models.CharField(max_length=100, verbose_name='Главный оффер')),
                ('button_text', models.CharField(max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка кнопки')),
                ('button_colour', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webjox_backend_promo.colours', verbose_name='Цвет кнопки')),
            ],
            options={
                'verbose_name': 'Главный блок',
                'verbose_name_plural': 'Главный блок',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название проекта')),
                ('screenshot', models.ImageField(upload_to='images/responses/screenshots', verbose_name='Скриншот')),
                ('response', models.ImageField(upload_to='images/responses/responses', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ServisesLeadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Услуга в лид-форме',
                'verbose_name_plural': 'Услуги в лид-форме',
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, verbose_name='Язык программирования')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_of_background', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webjox_backend_promo.colours', verbose_name='Цвет фона сайта')),
                ('font', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webjox_backend_promo.fonts', verbose_name='Шрифт сайта')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайт',
            },
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок блока')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('site', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webjox_backend_promo.site')),
            ],
            options={
                'verbose_name': 'Блок с отзывами',
                'verbose_name_plural': 'Блок с отзывами',
            },
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('description', models.TextField(max_length=200, verbose_name='Описание услуги')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('site', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webjox_backend_promo.site')),
            ],
            options={
                'verbose_name': 'Наша услуга',
                'verbose_name_plural': 'Наши услуги',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст оффера')),
                ('mainblock', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='webjox_backend_promo.mainblock')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
            },
        ),
        migrations.AddField(
            model_name='mainblock',
            name='site',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webjox_backend_promo.site'),
        ),
        migrations.CreateModel(
            name='LeadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок блока')),
                ('button_text', models.CharField(max_length=30, verbose_name='Текст кнопки')),
                ('button_colour', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webjox_backend_promo.colours', verbose_name='Цвет кнопки')),
                ('site', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webjox_backend_promo.site')),
            ],
            options={
                'verbose_name': 'Форма сбора заявок',
                'verbose_name_plural': 'Форма сбора заявок',
            },
        ),
        migrations.CreateModel(
            name='Keyses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Навзание кейса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/keyses/', verbose_name='Обложка кейса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание кейса')),
                ('frameworks', models.ManyToManyField(blank=True, null=True, to='webjox_backend_promo.frameworks', verbose_name='Фреймворки')),
                ('site', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webjox_backend_promo.site')),
                ('stack', models.ManyToManyField(blank=True, null=True, to='webjox_backend_promo.stack', verbose_name='Стек')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('signature', models.TextField(max_length=100, verbose_name='Подпись')),
                ('photo', models.ImageField(upload_to='images/interview/', verbose_name='Фото')),
                ('site', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webjox_backend_promo.site')),
            ],
            options={
                'verbose_name': 'Интервьюшка',
                'verbose_name_plural': 'Интервьюшка',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='images/header/', verbose_name='Лого в хэдере')),
                ('site', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webjox_backend_promo.site')),
            ],
            options={
                'verbose_name': 'Хэдер',
                'verbose_name_plural': 'Хэдер',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=None, null=True, verbose_name='Текст в футере')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Телефон')),
                ('tg_link', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Ссылка для ТГ')),
                ('wa_link', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Ссылка для Вотсапа')),
                ('site', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webjox_backend_promo.site')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
            },
        ),
        migrations.CreateModel(
            name='ElementMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название элемента меню')),
                ('link', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Якорь')),
                ('header', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='webjox_backend_promo.header')),
            ],
            options={
                'verbose_name': 'Элемент меню',
                'verbose_name_plural': 'Элементы меню',
            },
        ),
        migrations.CreateModel(
            name='DecidesOnFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Решение')),
                ('footer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webjox_backend_promo.footer')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
            },
        ),
        migrations.CreateModel(
            name='CooperationFormats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('button_text', models.CharField(max_length=20, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ссылка кнопки')),
                ('button_colour', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webjox_backend_promo.colours', verbose_name='Цвет кнопки')),
                ('site', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webjox_backend_promo.site')),
            ],
            options={
                'verbose_name': 'Формат сотрудничества',
                'verbose_name_plural': 'Форматы сотрудничества',
            },
        ),
    ]
