# Generated by Django 4.1 on 2022-08-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjox_backend_promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyses',
            name='frameworks',
            field=models.ManyToManyField(blank=True, to='webjox_backend_promo.frameworks', verbose_name='Фреймворки'),
        ),
        migrations.AlterField(
            model_name='keyses',
            name='stack',
            field=models.ManyToManyField(blank=True, to='webjox_backend_promo.stack', verbose_name='Стек'),
        ),
    ]
