# Generated by Django 4.1 on 2022-08-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjox_backend_promo', '0002_alter_keyses_frameworks_alter_keyses_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название проекта')),
                ('screenshot', models.ImageField(upload_to='images/feedbacks/screenshots', verbose_name='Скриншот')),
                ('mail', models.ImageField(upload_to='images/feedbacks/mails', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.RenameModel(
            old_name='Responses',
            new_name='Feedbacks',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
