# Generated by Django 4.1 on 2022-08-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webjox_backend_promo', '0003_feedback_rename_responses_feedbacks_delete_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedbacks',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webjox_backend_promo.feedbacks'),
        ),
    ]
