# Generated by Django 4.1 on 2022-08-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webjox_backend_promo', '0006_cooperationformats_separator_feedbacks_separator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='logo',
        ),
    ]
