# Generated by Django 4.1 on 2022-08-23 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webjox_backend_promo', '0008_alter_offers_mainblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='mainblock',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers_mainblock', to='webjox_backend_promo.mainblock'),
        ),
    ]
