# Generated by Django 4.1 on 2022-08-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webjox_backend_promo', '0010_alter_mainblock_button_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationformats',
            name='button_colour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperations_button_colour', to='webjox_backend_promo.colours', verbose_name='Цвет кнопки'),
        ),
        migrations.AlterField(
            model_name='decidesonfooter',
            name='footer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decides_footer', to='webjox_backend_promo.footer'),
        ),
        migrations.AlterField(
            model_name='elementmenu',
            name='header',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='header_menu', to='webjox_backend_promo.header'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbacks',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='every_feedbacks', to='webjox_backend_promo.feedbacks'),
        ),
        migrations.AlterField(
            model_name='leadform',
            name='button_colour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadform_button_colour', to='webjox_backend_promo.colours', verbose_name='Цвет кнопки'),
        ),
        migrations.AlterField(
            model_name='servisesleadform',
            name='leadform',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_leadform', to='webjox_backend_promo.leadform'),
        ),
        migrations.AlterField(
            model_name='site',
            name='colour_of_background',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_font', to='webjox_backend_promo.colours', verbose_name='Цвет фона сайта'),
        ),
    ]
