# Generated by Django 4.1 on 2022-08-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webjox_backend_promo', '0011_alter_cooperationformats_button_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainblock',
            name='button_colour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buttoncolour', to='webjox_backend_promo.colours', verbose_name='Цвет кнопки'),
        ),
    ]
