# Generated by Django 4.1 on 2022-08-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webjox_backend_promo', '0013_alter_mainblock_button_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='tg_link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Ссылка для ТГ'),
        ),
        migrations.AddField(
            model_name='interview',
            name='wa_link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Ссылка для Вотсапа'),
        ),
    ]
